"""Compile embedded PTX with NVIDIA NVRTC at build time (no GPU required)."""
import argparse
import ctypes as ct
import importlib.util
import os
from pathlib import Path


def load_nvrtc():
    spec = importlib.util.find_spec("nvidia.cuda_nvrtc")
    if spec is None or spec.submodule_search_locations is None:
        raise RuntimeError("Install the build dependency: python -m pip install nvidia-cuda-nvrtc-cu12==12.6.85")
    root = Path(next(iter(spec.submodule_search_locations)))
    candidates = list(root.rglob("nvrtc64_*.dll")) if os.name == "nt" else list(root.rglob("libnvrtc.so*"))
    if not candidates:
        raise RuntimeError("NVIDIA NVRTC library not found in " + str(root))
    path = sorted(candidates)[0]
    # Keep the DLL search cookie alive until compilation finishes.
    cookie = os.add_dll_directory(str(path.parent)) if os.name == "nt" else None
    lib = ct.CDLL(str(path))
    signatures = {
        "nvrtcCreateProgram": [ct.POINTER(ct.c_void_p), ct.c_char_p, ct.c_char_p, ct.c_int, ct.POINTER(ct.c_char_p), ct.POINTER(ct.c_char_p)],
        "nvrtcCompileProgram": [ct.c_void_p, ct.c_int, ct.POINTER(ct.c_char_p)],
        "nvrtcGetProgramLogSize": [ct.c_void_p, ct.POINTER(ct.c_size_t)],
        "nvrtcGetProgramLog": [ct.c_void_p, ct.c_void_p],
        "nvrtcGetPTXSize": [ct.c_void_p, ct.POINTER(ct.c_size_t)],
        "nvrtcGetPTX": [ct.c_void_p, ct.c_void_p],
        "nvrtcDestroyProgram": [ct.POINTER(ct.c_void_p)],
    }
    for name, args in signatures.items():
        getattr(lib, name).argtypes = args
        getattr(lib, name).restype = ct.c_int
    return lib, cookie


def check(code):
    if code:
        raise RuntimeError(f"NVRTC error {code}")


def compile_ptx(lib, source, shared, mode):
    program = ct.c_void_p()
    headers = (ct.c_char_p * 1)(shared)
    names = (ct.c_char_p * 1)(b"secp256k1_tron.cl")
    check(lib.nvrtcCreateProgram(ct.byref(program), source, b"tron_vanity_cuda.cu", 1, headers, names))
    try:
        # Baseline PTX is forward compatible with newer NVIDIA architectures.
        options = [b"--std=c++14", b"--gpu-architecture=compute_52", f"-DRESIDENT_RNG={mode}".encode()]
        args = (ct.c_char_p * len(options))(*options)
        result = lib.nvrtcCompileProgram(program, len(options), args)
        size = ct.c_size_t()
        check(lib.nvrtcGetProgramLogSize(program, ct.byref(size)))
        log = ct.create_string_buffer(size.value)
        check(lib.nvrtcGetProgramLog(program, log))
        if result:
            raise RuntimeError(log.value.decode(errors="replace"))
        check(lib.nvrtcGetPTXSize(program, ct.byref(size)))
        ptx = ct.create_string_buffer(size.value)
        check(lib.nvrtcGetPTX(program, ptx))
        text = ptx.value.decode("ascii")
        for entry in ("tron_vanity_resident_seed", "tron_vanity_resident_probe"):
            if f".entry {entry}(" not in text:
                raise RuntimeError("Missing CUDA entry point: " + entry)
        print(f"CUDA RNG {mode}: compiled {len(text)} bytes of PTX", flush=True)
        return text
    finally:
        check(lib.nvrtcDestroyProgram(ct.byref(program)))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-dir", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    lib, cookie = load_nvrtc()
    source = (args.source_dir / "tron_vanity_cuda.cu").read_bytes()
    shared = (args.source_dir / "secp256k1_tron.cl").read_bytes()
    ptx = [compile_ptx(lib, source, shared, mode) for mode in (1, 2, 3)]
    header = "// Generated by scripts/build_cuda_ptx.py; do not edit.\n#pragma once\n"
    # Separate literals avoid MSVC's per-literal/concatenated-string limit.
    for mode, text in enumerate(ptx, 1):
        header += f"static const char* const kCudaPtx{mode}[] = {{\n"
        header += ",\n".join('R"CUDA_PTX(' + text[i:i + 8000] + ')CUDA_PTX"'
                              for i in range(0, len(text), 8000)) + ",\nnullptr};\n"
    header += "static const char* const* const kCudaPtx[] = {kCudaPtx1, kCudaPtx2, kCudaPtx3};\n"
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(header, encoding="ascii")
    if cookie:
        cookie.close()


if __name__ == "__main__":
    main()
