# Embed a compiler-produced binary SPIR-V module as portable 32-bit words.
file(READ "${IN}" HEXDATA HEX)
string(LENGTH "${HEXDATA}" HEXLEN)
math(EXPR BYTES "${HEXLEN} / 2")
math(EXPR REMAINDER "${BYTES} % 4")
if(NOT REMAINDER EQUAL 0)
  message(FATAL_ERROR "SPIR-V byte length is not divisible by four")
endif()
math(EXPR LAST "${BYTES} / 4 - 1")
set(WORDS "")
foreach(I RANGE 0 ${LAST})
  math(EXPR OFFSET "${I} * 8")
  string(SUBSTRING "${HEXDATA}" ${OFFSET} 2 B0)
  math(EXPR OFFSET1 "${OFFSET} + 2")
  math(EXPR OFFSET2 "${OFFSET} + 4")
  math(EXPR OFFSET3 "${OFFSET} + 6")
  string(SUBSTRING "${HEXDATA}" ${OFFSET1} 2 B1)
  string(SUBSTRING "${HEXDATA}" ${OFFSET2} 2 B2)
  string(SUBSTRING "${HEXDATA}" ${OFFSET3} 2 B3)
  string(APPEND WORDS "0x${B3}${B2}${B1}${B0}u,")
endforeach()
file(WRITE "${OUT}" "#pragma once\n#include <cstdint>\nstatic constexpr std::uint32_t kVulkanProbeSpv[] = {${WORDS}};\n")
